[peer]
id    = "2"
peers = 2


[hardware]
addr        = 15658
sim         = true
num_floors  = 4


[elevator]
addr            = "localhost:15658"
num_floors      = 4
door_open_s     = 3
door_timout_s   = 10
motor_timeout_s = 10


[network]
peers       = 3
# host is set to either localhost/127.0.0.1 or the lab server.
host        = "0.0.0.0"
udp_send    = "0.0.0.0:2000"
udp_recv    = "0.0.0.0:2002"


[backup]
pri_send        = "localhost:4101"
sec_recv        = "localhost:4102"
attempts        = 3
sleep_dur_milli = 100