[hardware]
addr        = "localhost:15657"
sim         = true
num_floors  = 4


[elevator]
addr            = "localhost:15657"
num_floors      = 4
door_open_s     = 3
door_timout_s   = 10
motor_timeout_s = 10


[network]
peers       = 3
host        = "127.0.0.1"
udp_send    = 40012
udp_recv    = 40012


[backup]
pri_send        = "localhost:"
sec_recv        = "localhost:"
attempts        = 3
sleep_dur_milli = 1000