<<<<<<< HEAD
[peer]
id = 1


[hardware]
addr        = 15657
=======
[hardware]
addr        = "localhost:15657"
>>>>>>> 9ca0225 (fixed some errors from the lab)
sim         = true
num_floors  = 4


[elevator]
addr            = "localhost:15657"
num_floors      = 4
door_open_s     = 3
door_timout_s   = 10
motor_timeout_s = 10


[network]
peers       = 3
host        = "127.0.0.1"
udp_send    = 40012
udp_recv    = 40012


[backup]
<<<<<<< HEAD
pri_send        = "localhost:40000"
sec_recv        = "localhost:40001"
=======
pri_send        = "localhost:"
sec_recv        = "localhost:"
>>>>>>> 9ca0225 (fixed some errors from the lab)
attempts        = 3
sleep_dur_milli = 1000