[peer]
id    = "0"

[hardware]
addr        = 15657
sim         = true
load_time   = 1000


[elevator]
addr            = "localhost:15657"
num_floors      = 4
door_open_s     = 3
door_timout_s   = 10
motor_timeout_s = 10


[network]
peers       = 3
# host is set to either localhost/127.0.0.1 or the lab server.
udp_send    = "0.0.0.0:2000"
udp_recv    = "0.0.0.0:2001"
hb_time     = 100
state_time  = 200

[backup]
pri_send        = "localhost:4099"
sec_recv        = "localhost:4100"
attempts        = 3
sleep_dur_milli = 1000